"use strict";
console.log(5 + 3);
console.log(10 - 2);
console.log(2 * 4);
console.log(16 / 2);
// let number1: number = 16;
// let number2: number = 2;
// console.log(number1 / number2);
// console.log(number1 - number2);
// console.log(number1 * number2);
// console.log(number2 / number1);
